"use client";

import { ArrowUpRight, Check, ChevronDown } from "lucide-react";
import { useEffect, useRef, useState } from "react";

function PremiumSelect({label,name,placeholder,options}:{label:string;name:string;placeholder:string;options:string[]}){
  const [open,setOpen]=useState(false); const [value,setValue]=useState(""); const root=useRef<HTMLDivElement>(null);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(root.current&&!root.current.contains(event.target as Node))setOpen(false)}; const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)}; document.addEventListener("mousedown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",escape)}},[]);
  return <div className={"valuation-select "+(open?"open":"")} ref={root}><span>{label}</span><button type="button" onClick={()=>setOpen(state=>!state)} aria-haspopup="listbox" aria-expanded={open}><b>{value||placeholder}</b><ChevronDown aria-hidden="true"/></button>{open&&<div role="listbox">{options.map(option=><button type="button" role="option" aria-selected={value===option} className={value===option?"active":""} key={option} onClick={()=>{setValue(option);setOpen(false)}}><span>{option}</span>{value===option&&<Check aria-hidden="true"/>}</button>)}</div>}<input type="hidden" name={name} value={value}/></div>;
}

export function ValuationFormExperience(){return <form className="valuation-premium-form"><header><span>05 / DATOS DE LA PROPIEDAD</span><h2>Recibí una primera lectura profesional.</h2><p>Completá lo que tengas. El resto lo relevamos juntos durante la entrevista.</p></header><div className="valuation-form-grid"><label><span>NOMBRE Y APELLIDO</span><input placeholder="Tu nombre" required/></label><label><span>TELÉFONO</span><input type="tel" placeholder="+54 9 11" required/></label><label><span>EMAIL</span><input type="email" placeholder="nombre@email.com"/></label><label><span>ZONA</span><input placeholder="Barrio o localidad" required/></label><PremiumSelect label="OPERACIÓN" name="operacion" placeholder="Seleccioná" options={["Venta","Alquiler"]}/><PremiumSelect label="TIPO DE PROPIEDAD" name="tipo" placeholder="Seleccioná" options={["Casa","Departamento","PH","Terreno","Local","Oficina"]}/><label><span>SUPERFICIE APROX.</span><input placeholder="Ej. 180 m²"/></label><label><span>AMBIENTES</span><input placeholder="Ej. 4"/></label><label><span>ANTIGÜEDAD</span><input placeholder="Ej. 8 años"/></label><PremiumSelect label="ESTADO GENERAL" name="estado" placeholder="Seleccioná" options={["A estrenar","Excelente","Muy bueno","Bueno","A refaccionar"]}/><label><span>DIRECCIÓN APROXIMADA</span><input placeholder="Calle y altura"/></label><label className="wide"><span>COMENTARIOS</span><textarea rows={4} placeholder="Contanos si tiene cochera, jardín, amenities, mejoras recientes u otra información relevante"/></label><button type="submit">SOLICITAR TASACIÓN <ArrowUpRight aria-hidden="true"/></button></div></form>}