"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import { ArrowRight, Eye, EyeOff, KeyRound, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { Brand } from "../site-chrome";

export function AdminLogin(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"No se pudo ingresar.");window.location.assign("/admin");}catch(value){setError(value instanceof Error?value.message:"No se pudo ingresar.");}finally{setBusy(false);}}return <main className="admin-auth-screen"><section className="admin-auth-brand"><Brand/><div><span>GESTI?N INMOBILIARIA</span><h1>Todo el negocio,<br/>en un solo lugar.</h1><p>Publicaciones, consultas y proyectos con un acceso simple y protegido.</p></div><ShieldCheck/></section><section className="admin-auth-panel"><div className="admin-auth-card"><p>ACCESO PRIVADO</p><h2>Ingres? al panel.</h2><span>Us? el email y la contrase?a de administraci?n.</span>{error&&<div className="admin-auth-error">{error}</div>}<form onSubmit={submit}><label><b>EMAIL</b><div><Mail/><input type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} required placeholder="nombre@empresa.com"/></div></label><label><b>CONTRASE?A</b><div><LockKeyhole/><input type={show?"text":"password"} autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} required/><button type="button" onClick={()=>setShow(value=>!value)} aria-label={show?"Ocultar contrase?a":"Mostrar contrase?a"}>{show?<EyeOff/>:<Eye/>}</button></div></label><button className="admin-auth-submit" disabled={busy}>{busy?"Verificando...":<>Ingresar <ArrowRight/></>}</button></form><a className="admin-auth-recovery" href="/admin/recuperar">?Olvidaste tu contrase?a?</a></div><Link className="admin-auth-back" href="/">? Volver al sitio p?blico</Link></section></main>}

export function PasswordReset({email,initial=false}:{email:string;initial?:boolean}){const[password,setPassword]=useState("");const[confirmation,setConfirmation]=useState("");const[show,setShow]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/auth/reset-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password,confirmation})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"No se pudo guardar.");window.location.assign("/admin");}catch(value){setError(value instanceof Error?value.message:"No se pudo guardar.");}finally{setBusy(false);}}return <main className="admin-auth-screen"><section className="admin-auth-brand"><Brand/><div><span>{initial?"ACTIVACI?N SEGURA":"RECUPERACI?N SEGURA"}</span><h1>{initial?"Cre? tu acceso.":"Volv? a entrar."}</h1><p>Tu identidad ya fue verificada. La contrase?a se almacena protegida y nunca puede leerse desde el sistema.</p></div><KeyRound/></section><section className="admin-auth-panel"><div className="admin-auth-card"><p>{initial?"PRIMER INGRESO":"NUEVA CONTRASE?A"}</p><h2>{initial?"Defin? tu contrase?a.":"Restablec? tu contrase?a."}</h2><span>Cuenta: <strong>{email}</strong></span>{error&&<div className="admin-auth-error">{error}</div>}<form onSubmit={submit}><label><b>NUEVA CONTRASE?A</b><div><LockKeyhole/><input type={show?"text":"password"} autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} required minLength={10}/><button type="button" onClick={()=>setShow(value=>!value)}>{show?<EyeOff/>:<Eye/>}</button></div><small>M?nimo 10 caracteres, con letras y un n?mero.</small></label><label><b>REPETIR CONTRASE?A</b><div><ShieldCheck/><input type={show?"text":"password"} autoComplete="new-password" value={confirmation} onChange={event=>setConfirmation(event.target.value)} required minLength={10}/></div></label><button className="admin-auth-submit" disabled={busy}>{busy?"Guardando...":<>Guardar y entrar <ArrowRight/></>}</button></form></div></section></main>}

export function RecoveryVerification({verificationPath}:{verificationPath:string}){return <main className="admin-auth-screen"><section className="admin-auth-brand"><Brand/><div><span>RECUPERACI?N SEGURA</span><h1>Primero,<br/>tu identidad.</h1><p>Confirmaremos la cuenta administradora antes de permitir una nueva contrase?a.</p></div><ShieldCheck/></section><section className="admin-auth-panel"><div className="admin-auth-card"><p>PASO DE SEGURIDAD</p><h2>Verific? tu cuenta.</h2><span>Esta comprobaci?n protege las propiedades, consultas e informaci?n del negocio.</span><a className="admin-auth-submit" href={verificationPath}>Verificar identidad <ArrowRight/></a><Link className="admin-auth-recovery" href="/admin">Volver al ingreso</Link></div></section></main>}
