"use client";

import { ArrowLeft, ArrowRight, ArrowUpRight, Building2, Check, Copy, Eye, FileText, Image as ImageIcon, LoaderCircle, MapPin, Pencil, Plus, Sparkles, Star, Trash2, Upload, X } from "lucide-react";
import { useEffect, useState, type ChangeEvent } from "react";
import { formatDevelopmentPrice, type Development } from "../developments";

type PublicationStatus = "published" | "draft";
type AdminDevelopment = Development & { publicationStatus: PublicationStatus };
type Draft = AdminDevelopment & { id?: number; descriptionText:string; amenitiesText:string; specificationsText:string };
const PUBLIC_SITE="https://inmobiliaria.ideamos.ar";
const empty:Draft={id:undefined,slug:"",title:"",location:"",neighborhood:"",status:"EN POZO",delivery:"A confirmar",units:"1 a 3 ambientes",currency:"USD",priceValue:0,pricePrefix:"Desde",priceSuffix:"",price:"",image:"",gallery:[],floors:"",apartments:"",garages:"",developer:"",architect:"",description:[],amenities:[],specifications:[],descriptionText:"",amenitiesText:"",specificationsText:"",publicationStatus:"draft"};
function slugify(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");}
function draftFrom(item?:AdminDevelopment):Draft{return item?{...item,gallery:item.gallery??[],descriptionText:item.description.join("\n"),amenitiesText:item.amenities.join(", "),specificationsText:item.specifications.join(", ")}:{...empty,gallery:[]};}

export function DevelopmentManager(){
 const [items,setItems]=useState<AdminDevelopment[]>([]),[draft,setDraft]=useState<Draft>(draftFrom()),[open,setOpen]=useState(false),[step,setStep]=useState<1|2|3>(1),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[notice,setNotice]=useState("");
 const update=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}));
 async function load(){setLoading(true);try{const response=await fetch("/api/admin/developments",{cache:"no-store"});const data=await response.json() as {developments?:AdminDevelopment[];error?:string};if(!response.ok||!data.developments)throw new Error(data.error||"No se pudieron cargar.");setItems(data.developments);}catch(error){setNotice(error instanceof Error?error.message:"No se pudieron cargar los emprendimientos.");}finally{setLoading(false);}}
 useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[]);
 function create(){setDraft(draftFrom());setStep(1);setOpen(true);} function edit(item:AdminDevelopment){setDraft(draftFrom(item));setStep(1);setOpen(true);} function duplicate(item:AdminDevelopment){setDraft({...draftFrom(item),id:undefined,title:item.title+" copia",slug:"",publicationStatus:"draft"});setStep(1);setOpen(true);}
 function go(next:1|2|3){if(next>1&&(!draft.title.trim()||!draft.location.trim())){setNotice("Complet? el nombre y la ubicaci?n para continuar.");return;}setStep(next);}
 async function save(status?:PublicationStatus){const publicationStatus=status??draft.publicationStatus;if(!draft.title.trim()||!draft.location.trim()){setNotice("Complet? el nombre y la ubicaci?n.");return;}if(publicationStatus==="published"&&!draft.image){setNotice("Agreg? una portada antes de publicar.");return;}setSaving(true);setNotice("");const payload={...draft,slug:draft.slug||slugify(draft.title),publicationStatus,description:draft.descriptionText.split("\n").map(x=>x.trim()).filter(Boolean),amenities:draft.amenitiesText.split(",").map(x=>x.trim()).filter(Boolean),specifications:draft.specificationsText.split(",").map(x=>x.trim()).filter(Boolean)};try{const response=await fetch("/api/admin/developments",{method:draft.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {development?:AdminDevelopment;error?:string};if(!response.ok||!data.development)throw new Error(data.error||"No se pudo guardar.");setItems(current=>draft.id?current.map(item=>item.id===draft.id?data.development!:item):[data.development!,...current]);setOpen(false);setNotice(publicationStatus==="draft"?"Borrador guardado.":"Emprendimiento publicado.");}catch(error){setNotice(error instanceof Error?error.message:"No se pudo guardar.");}finally{setSaving(false);}}
 async function remove(item:AdminDevelopment){if(!window.confirm(`?Eliminar ${item.title}? Esta acci?n no se puede deshacer.`))return;const response=await fetch(`/api/admin/developments?id=${item.id}`,{method:"DELETE"});if(response.ok){setItems(current=>current.filter(x=>x.id!==item.id));setNotice("Emprendimiento eliminado.");}else setNotice("No se pudo eliminar.");}
 async function upload(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files??[]);event.target.value="";if(!files.length)return;setUploading(true);const body=new FormData();files.forEach(file=>body.append("files",file));try{const response=await fetch("/api/admin/uploads",{method:"POST",body});const data=await response.json() as {urls?:string[];error?:string};if(!response.ok||!data.urls?.length)throw new Error(data.error||"No se pudieron cargar.");setDraft(current=>{const all=[current.image,...current.gallery,...data.urls!].filter(Boolean);return{...current,image:all[0]??"",gallery:all.slice(1)}});}catch(error){setNotice(error instanceof Error?error.message:"No se pudieron cargar las im?genes.");}finally{setUploading(false);}}
 function primary(url:string){setDraft(current=>({ ...current,image:url,gallery:[current.image,...current.gallery.filter(item=>item!==url)].filter(Boolean)}));}
 function removeImage(url:string){setDraft(current=>{const all=[current.image,...current.gallery].filter(item=>item!==url);return{...current,image:all[0]??"",gallery:all.slice(1)}});}
 return <><section className="admin-content-card admin-module-card development-manager"><div className="admin-list-head"><div><p>PORTFOLIO DE PROYECTOS</p><h2>Emprendimientos</h2><span>Cre?, edit? y public? cada proyecto desde el mismo panel.</span></div><div className="development-head-actions"><a href={`${PUBLIC_SITE}/emprendimientos`} target="_blank" rel="noreferrer">Ver cat?logo <ArrowUpRight/></a><button type="button" onClick={create}><Plus/> Nuevo emprendimiento</button></div></div>{notice&&<p className="admin-inline-notice">{notice}</p>}<div className={`admin-development-grid ${loading?"loading":""}`}>{items.map(item=><article key={item.id}><div className="admin-development-image">{item.image?<img src={item.image} alt=""/>:<ImageIcon/>}<span className={item.publicationStatus}>{item.publicationStatus==="published"?"PUBLICADO":"BORRADOR"}</span></div><div><small>{item.status}</small><h3>{item.title}</h3><p><MapPin/>{item.location}</p><dl><div><dt>UNIDADES</dt><dd>{item.units}</dd></div><div><dt>ENTREGA</dt><dd>{item.delivery}</dd></div></dl><strong>{formatDevelopmentPrice(item)}</strong><footer><button onClick={()=>edit(item)} aria-label="Editar" type="button"><Pencil/></button><button onClick={()=>duplicate(item)} aria-label="Duplicar" type="button"><Copy/></button>{item.publicationStatus==="published"&&<a href={`${PUBLIC_SITE}/emprendimientos/${item.slug}`} target="_blank" rel="noreferrer" aria-label="Ver"><Eye/></a>}<button className="danger" onClick={()=>void remove(item)} aria-label="Eliminar" type="button"><Trash2/></button></footer></div></article>)}</div>{!loading&&!items.length&&<div className="admin-empty"><Building2/><h3>Todav?a no hay emprendimientos.</h3><button type="button" onClick={create}><Plus/> Crear el primero</button></div>}</section>
 {open&&<div className="admin-editor-layer" role="dialog" aria-modal="true" aria-label="Editor de emprendimiento"><button className="admin-editor-backdrop" type="button" onClick={()=>setOpen(false)} aria-label="Cerrar"/><form className="admin-editor development-editor" onSubmit={event=>{event.preventDefault();void save();}}><header><div><p>{draft.id?`REF. EMP-${String(draft.id).padStart(4,"0")}`:"NUEVO PROYECTO"}</p><h2>{draft.id?"Editar emprendimiento":"Crear emprendimiento"}</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></header><div className="admin-editor-progress"><button type="button" className={step===1?"active":"complete"} onClick={()=>go(1)}><b>1</b>Informaci?n</button><i/><button type="button" className={step===2?"active":step>2?"complete":""} onClick={()=>go(2)}><b>2</b>Ficha t?cnica</button><i/><button type="button" className={step===3?"active":""} onClick={()=>go(3)}><b>3</b>Im?genes</button></div><div className="admin-editor-body">
 {step===1&&<section><div className="admin-form-title"><span>01</span><div><h3>Informaci?n comercial</h3><p>Identidad, etapa y valor del proyecto.</p></div></div><div className="admin-form-grid"><label className="wide"><span>NOMBRE DEL EMPRENDIMIENTO</span><input value={draft.title} onChange={e=>update("title",e.target.value)} required/></label><label><span>UBICACI?N</span><input value={draft.location} onChange={e=>update("location",e.target.value)} required/></label><label><span>BARRIO / LOCALIDAD</span><input value={draft.neighborhood} onChange={e=>update("neighborhood",e.target.value)}/></label><label><span>ESTADO DE OBRA</span><input value={draft.status} onChange={e=>update("status",e.target.value)} placeholder="EN POZO"/></label><label><span>ENTREGA</span><input value={draft.delivery} onChange={e=>update("delivery",e.target.value)} placeholder="2028"/></label><label className="wide"><span>TIPOLOG?AS / UNIDADES</span><input value={draft.units} onChange={e=>update("units",e.target.value)} placeholder="1 a 4 ambientes"/></label><label><span>MONEDA</span><select value={draft.currency} onChange={e=>update("currency",e.target.value as "USD"|"ARS")}><option>USD</option><option>ARS</option></select></label><div className="admin-price-composer wide"><label><span>TEXTO ANTES</span><input value={draft.pricePrefix??""} onChange={e=>update("pricePrefix",e.target.value)} placeholder="Desde"/></label><label><span>PRECIO</span><input type="number" min="0" value={draft.priceValue??0} onChange={e=>update("priceValue",Number(e.target.value))}/></label><label><span>TEXTO DESPU?S</span><input value={draft.priceSuffix??""} onChange={e=>update("priceSuffix",e.target.value)} placeholder="x mes"/></label></div><label className="wide"><span>ENLACE / SLUG</span><input value={draft.slug} onChange={e=>update("slug",slugify(e.target.value))} placeholder="Se genera autom?ticamente"/></label></div></section>}
 {step===2&&<section><div className="admin-form-title"><span>02</span><div><h3>Ficha del proyecto</h3><p>Datos t?cnicos, equipo y atributos destacados.</p></div></div><div className="admin-form-grid"><label><span>PISOS / ESCALA</span><input value={draft.floors} onChange={e=>update("floors",e.target.value)}/></label><label><span>CANTIDAD DE UNIDADES</span><input value={draft.apartments} onChange={e=>update("apartments",e.target.value)}/></label><label><span>COCHERAS</span><input value={draft.garages} onChange={e=>update("garages",e.target.value)}/></label><label><span>DESARROLLADOR</span><input value={draft.developer} onChange={e=>update("developer",e.target.value)}/></label><label className="wide"><span>ESTUDIO DE ARQUITECTURA</span><input value={draft.architect} onChange={e=>update("architect",e.target.value)}/></label><label className="wide"><span>DESCRIPCI?N (UN P?RRAFO POR L?NEA)</span><textarea value={draft.descriptionText} onChange={e=>update("descriptionText",e.target.value)}/></label><label className="wide"><span>AMENITIES, SEPARADOS POR COMAS</span><input value={draft.amenitiesText} onChange={e=>update("amenitiesText",e.target.value)}/></label><label className="wide"><span>CALIDADES, SEPARADAS POR COMAS</span><input value={draft.specificationsText} onChange={e=>update("specificationsText",e.target.value)}/></label></div></section>}
 {step===3&&<section><div className="admin-form-title"><span>03</span><div><h3>Galer?a y publicaci?n</h3><p>Eleg? la portada, orden? la selecci?n y public?.</p></div></div><div className="admin-upload-zone"><label className={uploading?"uploading":""}><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple onChange={upload} disabled={uploading}/>{uploading?<LoaderCircle className="spin"/>:<Upload/>}<b>{uploading?"Cargando im?genes...":"Seleccionar im?genes"}</b><span>La primera imagen ser? la portada</span></label><div className="admin-url-field"><span>O PEG? UNA URL EXTERNA</span><div><input value={draft.image.startsWith("http")?draft.image:""} onChange={e=>update("image",e.target.value)} placeholder="https://..."/><ImageIcon/></div></div></div><div className="admin-gallery-manager">{[draft.image,...draft.gallery].filter(Boolean).map((url,index)=><article key={url+index} className={index===0?"primary":""}><img src={url} alt=""/><span>{index===0?"PORTADA":String(index+1).padStart(2,"0")}</span>{index!==0&&<button type="button" onClick={()=>primary(url)}><Star/> Portada</button>}<button className="remove" type="button" onClick={()=>removeImage(url)}><X/></button></article>)}</div><div className="admin-publication-settings"><label><span>ESTADO</span><select value={draft.publicationStatus} onChange={e=>update("publicationStatus",e.target.value as PublicationStatus)}><option value="published">Publicado</option><option value="draft">Borrador</option></select></label><div className="development-publication-tip"><Sparkles/><span><b>Vista p?blica conectada</b><small>Al publicar, la grilla y la ficha se actualizan en el dominio principal.</small></span></div></div></section>}
 </div><footer><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><div>{step>1&&<button type="button" onClick={()=>go((step-1) as 1|2)}><ArrowLeft/> Anterior</button>}{step<3?<button className="primary" type="button" onClick={()=>go((step+1) as 2|3)}>Siguiente <ArrowRight/></button>:<><button type="button" onClick={()=>void save("draft")} disabled={saving}><FileText/> Guardar borrador</button><button className="primary" type="submit" disabled={saving||uploading}>{saving?"Guardando...":<><Check/> Guardar emprendimiento</>}</button></>}</div></footer></form></div>}</>;
}
