import Link from "next/link";
import { getChatGPTUser, chatGPTSignInPath, chatGPTSignOutPath } from "../chatgpt-auth";
import { properties } from "../properties";
import { Brand } from "../site-chrome";

export const dynamic = "force-dynamic";

export default async function AdminPage() {
  if (process.env.GITHUB_PAGES === "true") return <main className="admin-login"><div><Brand/><p className="section-label">Panel privado</p><h1>Administraci&oacute;n disponible en la versi&oacute;n privada.</h1><p>GitHub Pages publica la experiencia comercial. La gesti&oacute;n segura permanece en el entorno administrable.</p><Link href="/">Volver al sitio</Link></div></main>;
  const user = await getChatGPTUser();
  if (!user) return <main className="admin-login"><div><Brand/><p className="section-label">Panel privado</p><h1>Administr&aacute; tu inmobiliaria.</h1><p>Este acceso ser&aacute; exclusivo para el equipo autorizado. Desde ac&aacute; vas a publicar propiedades, cambiar estados y revisar consultas.</p><a href={chatGPTSignInPath("/admin")}>Ingresar al panel &rarr;</a><br/><Link href="/">Volver al sitio</Link></div></main>;
  return <main className="admin-shell"><header className="admin-topbar"><Brand/><nav><Link href="/">Ver sitio</Link><a href={chatGPTSignOutPath("/")}>Cerrar sesi&oacute;n</a></nav></header><section className="admin-main"><div className="admin-heading"><div><p className="section-label">Panel general</p><h1>Hola, {user.fullName ?? "equipo"}.</h1><p>Todo lo importante de tu inmobiliaria, en un solo lugar.</p></div><button className="admin-button">+ Nueva propiedad</button></div><div className="admin-note"><strong>Primera versi&oacute;n del panel.</strong> Cuando nos confirmes el correo administrador, habilitamos la publicaci&oacute;n y edici&oacute;n real.</div><div className="admin-stats"><div className="admin-stat"><span>Propiedades activas</span><strong>{properties.length}</strong></div><div className="admin-stat"><span>Consultas del mes</span><strong>24</strong></div><div className="admin-stat"><span>Visitas esta semana</span><strong>1.8k</strong></div><div className="admin-stat"><span>Operaciones abiertas</span><strong>7</strong></div></div><div className="admin-table"><p className="section-label">Publicaciones recientes</p>{properties.map(p => <div className="admin-row" key={p.id}><img src={p.image} alt=""/><strong>{p.title}</strong><span>{p.location}</span><span>{p.operation}</span><span className="admin-status">&bull; Publicada</span></div>)}</div></section></main>;
}