import { desc, eq } from "drizzle-orm";
import { getChatGPTUser } from "../../../chatgpt-auth";
import { developments as seedDevelopments, formatDevelopmentPrice, type Development } from "../../../developments";
import { getDb } from "../../../../db";
import { developmentRecords } from "../../../../db/schema";
import { ensureDatabaseSchema } from "../../../../db/ensure-schema";

const ADMIN_EMAIL = "r.lavega@ideamos.com.ar";
type PublicationStatus = "published" | "draft";
type Payload = Partial<Development> & { id?: number; publicationStatus?: PublicationStatus };

async function authorized() { const user = await getChatGPTUser(); return Boolean(user && user.email.toLowerCase() === ADMIN_EMAIL); }
function slugify(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function strings(value: unknown) { if (Array.isArray(value)) return value.map(String).map(item=>item.trim()).filter(Boolean); if (typeof value === "string") return value.split(/[,\n]/).map(item=>item.trim()).filter(Boolean); return []; }
function parse(value: string) { try { return JSON.parse(value) as string[]; } catch { return []; } }
function serialize(row: typeof developmentRecords.$inferSelect): Development & { publicationStatus: PublicationStatus } {
  const result: Development & { publicationStatus: PublicationStatus } = { ...row, currency: row.currency as "USD"|"ARS", priceValue: row.priceValue, pricePrefix: row.pricePrefix, priceSuffix: row.priceSuffix, price: "", gallery: parse(row.gallery), description: parse(row.description), amenities: parse(row.amenities), specifications: parse(row.specifications), publicationStatus: row.publicationStatus as PublicationStatus };
  result.price = formatDevelopmentPrice(result); return result;
}
async function ensureSeeded() {
  await ensureDatabaseSchema(); const db=getDb();
  for (const item of seedDevelopments) await db.insert(developmentRecords).values({ slug:item.slug,title:item.title,location:item.location,neighborhood:item.neighborhood,status:item.status,delivery:item.delivery,units:item.units,currency:item.currency??"USD",priceValue:item.priceValue??0,pricePrefix:item.pricePrefix??"Desde",priceSuffix:item.priceSuffix??"",image:item.image,gallery:JSON.stringify(item.gallery),floors:item.floors,apartments:item.apartments,garages:item.garages,developer:item.developer,architect:item.architect,description:JSON.stringify(item.description),amenities:JSON.stringify(item.amenities),specifications:JSON.stringify(item.specifications),publicationStatus:"published" }).onConflictDoNothing({target:developmentRecords.slug});
}
function validate(payload: Payload) { if(!String(payload.title??"").trim()||!String(payload.location??"").trim()) return "Completá nombre y ubicación."; if(payload.publicationStatus!=="draft"&&!String(payload.image??"").trim()) return "Agregá una imagen principal antes de publicar."; if(Number(payload.priceValue??0)<0) return "Revisá el precio."; return null; }
function values(payload: Payload) { const title=String(payload.title??"").trim(); return { slug:slugify(String(payload.slug||title)),title,location:String(payload.location??"").trim(),neighborhood:String(payload.neighborhood??"").trim(),status:String(payload.status??"EN POZO").trim(),delivery:String(payload.delivery??"A confirmar").trim(),units:String(payload.units??"").trim(),currency:String(payload.currency??"USD"),priceValue:Number(payload.priceValue??0),pricePrefix:String(payload.pricePrefix??"").trim(),priceSuffix:String(payload.priceSuffix??"").trim(),image:String(payload.image??"").trim(),gallery:JSON.stringify(strings(payload.gallery)),floors:String(payload.floors??"").trim(),apartments:String(payload.apartments??"").trim(),garages:String(payload.garages??"").trim(),developer:String(payload.developer??"").trim(),architect:String(payload.architect??"").trim(),description:JSON.stringify(strings(payload.description)),amenities:JSON.stringify(strings(payload.amenities)),specifications:JSON.stringify(strings(payload.specifications)),publicationStatus:String(payload.publicationStatus??"published"),updatedAt:new Date().toISOString() }; }
export async function GET(){ if(!(await authorized()))return Response.json({error:"No autorizado"},{status:401}); try{await ensureSeeded();const rows=await getDb().select().from(developmentRecords).orderBy(desc(developmentRecords.updatedAt),desc(developmentRecords.id));return Response.json({developments:rows.map(serialize)});}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudieron cargar los emprendimientos"},{status:500});}}
export async function POST(request:Request){if(!(await authorized()))return Response.json({error:"No autorizado"},{status:401});try{const payload=await request.json() as Payload;const problem=validate(payload);if(problem)return Response.json({error:problem},{status:400});await ensureSeeded();const [created]=await getDb().insert(developmentRecords).values(values(payload)).returning();return Response.json({development:serialize(created)},{status:201});}catch(error){const message=error instanceof Error?error.message:"No se pudo crear";return Response.json({error:message.includes("UNIQUE")?"Ya existe un emprendimiento con ese enlace.":message},{status:500});}}
export async function PATCH(request:Request){if(!(await authorized()))return Response.json({error:"No autorizado"},{status:401});try{const payload=await request.json() as Payload;if(!payload.id)return Response.json({error:"Falta el identificador."},{status:400});const problem=validate(payload);if(problem)return Response.json({error:problem},{status:400});const [updated]=await getDb().update(developmentRecords).set(values(payload)).where(eq(developmentRecords.id,payload.id)).returning();if(!updated)return Response.json({error:"Emprendimiento no encontrado."},{status:404});return Response.json({development:serialize(updated)});}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo actualizar"},{status:500});}}
export async function DELETE(request:Request){if(!(await authorized()))return Response.json({error:"No autorizado"},{status:401});await ensureDatabaseSchema();const id=Number(new URL(request.url).searchParams.get("id"));if(!id)return Response.json({error:"Falta el identificador."},{status:400});const [deleted]=await getDb().delete(developmentRecords).where(eq(developmentRecords.id,id)).returning({id:developmentRecords.id});if(!deleted)return Response.json({error:"Emprendimiento no encontrado."},{status:404});return Response.json({ok:true});}
