import Link from "next/link";
import { ArrowUpRight, Building2, CalendarDays, Layers3, MapPin } from "lucide-react";
import { formatDevelopmentPrice } from "../developments";
import { getLiveDevelopments } from "../live-developments";
import { InternalHero } from "../internal-hero";
import { SiteFooter, SiteHeader } from "../site-chrome";

export const dynamic = "force-dynamic";

export default async function DevelopmentsPage() {
  const developments = await getLiveDevelopments();
  return <main><SiteHeader/><InternalHero section="06" label="EMPRENDIMIENTOS / INVERSI&Oacute;N" eyebrow="NUEVOS PROYECTOS / BUENOS AIRES" title={["Emprendimientos","con futuro."]} description="Proyectos seleccionados por ubicaci&oacute;n, arquitectura, respaldo y potencial de valor." metric={String(developments.length)} metricLabel="PROYECTOS ACTIVOS"/><section className="developments-page"><header className="developments-intro"><div><span className="section-tag">SELECCI&Oacute;N IDEAMOS</span><h2>Invert&iacute; hoy.<br/>Viv&iacute; lo que viene.</h2></div><p>Descubr&iacute; propuestas en pozo, en construcci&oacute;n y pr&oacute;ximas a entregar. Te acompa&ntilde;amos para comparar cada oportunidad con informaci&oacute;n clara.</p></header><div className="development-grid">{developments.map((item,index)=><article className="development-card" key={item.slug}><Link className="development-media" href={`/emprendimientos/${item.slug}`} aria-label={`Ver ${item.title}`}><img src={item.image} alt={item.title}/><span className="development-status">{item.status}</span><b className="development-index">{String(index+1).padStart(2,"0")}</b></Link><div className="development-copy"><p><MapPin aria-hidden="true"/>{item.location}</p><h3><Link href={`/emprendimientos/${item.slug}`}>{item.title}</Link></h3><div className="development-meta"><span><Layers3 aria-hidden="true"/><small>UNIDADES</small><b>{item.units}</b></span><span><CalendarDays aria-hidden="true"/><small>ENTREGA</small><b>{item.delivery}</b></span></div><footer><strong>{formatDevelopmentPrice(item)}</strong><Link href={`/emprendimientos/${item.slug}`} aria-label={`Ver detalle de ${item.title}`}><ArrowUpRight aria-hidden="true"/></Link></footer></div></article>)}</div><section className="developments-cta"><Building2 aria-hidden="true"/><div><p>ASESORAMIENTO PARA INVERSORES</p><h2>Eleg&iacute; con informaci&oacute;n.<br/>Invert&iacute; con criterio.</h2></div><Link href="/contacto">Hablemos <ArrowUpRight aria-hidden="true"/></Link></section></section><SiteFooter/></main>;
}