import Link from "next/link";
import { ArrowUpRight, Building2, CalendarDays, Layers3, MapPin } from "lucide-react";
import { SiteFooter, SiteHeader } from "../site-chrome";
import { InternalHero } from "../internal-hero";

export const dynamic = "force-static";

const developments = [
  { slug:"distrito-aura-palermo", title:"Distrito Aura", location:"Palermo, CABA", status:"EN POZO", delivery:"2028", units:"1 a 4 ambientes", price:"Desde USD 128.000", image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1500&q=88" },
  { slug:"rio-norte-vicente-lopez", title:"Río Norte", location:"Vicente López, Buenos Aires", status:"EN CONSTRUCCIÓN", delivery:"2027", units:"2 a 5 ambientes", price:"Desde USD 198.000", image:"https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1500&q=88" },
  { slug:"casa-parque-san-isidro", title:"Casa Parque", location:"San Isidro, Buenos Aires", status:"ÚLTIMAS UNIDADES", delivery:"2026", units:"3 y 4 ambientes", price:"Desde USD 285.000", image:"https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1500&q=88" },
  { slug:"nexo-belgrano", title:"Nexo Belgrano", location:"Belgrano, CABA", status:"EN POZO", delivery:"2028", units:"1 a 3 ambientes", price:"Desde USD 112.000", image:"https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1500&q=88" },
  { slug:"lagos-residences-nordelta", title:"Lagos Residences", location:"Nordelta, Tigre", status:"EN CONSTRUCCIÓN", delivery:"2027", units:"2 a 4 ambientes", price:"Desde USD 210.000", image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1500&q=88" },
  { slug:"pasaje-colegiales", title:"Pasaje Colegiales", location:"Colegiales, CABA", status:"PRÓXIMA ENTREGA", delivery:"2026", units:"Estudios a 3 ambientes", price:"Desde USD 138.000", image:"https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1500&q=88" },
  { slug:"olivos-central", title:"Olivos Central", location:"Olivos, Buenos Aires", status:"EN POZO", delivery:"2029", units:"2 a 4 ambientes", price:"Desde USD 175.000", image:"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1500&q=88" },
  { slug:"puerto-madero-dock", title:"Dock 08", location:"Puerto Madero, CABA", status:"ÚLTIMAS UNIDADES", delivery:"2026", units:"2 a 5 ambientes", price:"Desde USD 360.000", image:"https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1500&q=88" },
];

export default function DevelopmentsPage() {
  return <main><SiteHeader/><InternalHero section="06" label="EMPRENDIMIENTOS / INVERSI&Oacute;N" eyebrow="NUEVOS PROYECTOS / BUENOS AIRES" title={["Emprendimientos","con futuro."]} description="Proyectos seleccionados por ubicaci&oacute;n, arquitectura, respaldo y potencial de valor." metric={String(developments.length)} metricLabel="PROYECTOS ACTIVOS"/><section className="developments-page"><header className="developments-intro"><div><span className="section-tag">SELECCI&Oacute;N IDEAMOS</span><h2>Invert&iacute; hoy.<br/>Viv&iacute; lo que viene.</h2></div><p>Descubr&iacute; propuestas en pozo, en construcci&oacute;n y pr&oacute;ximas a entregar. Te acompa&ntilde;amos para comparar cada oportunidad con informaci&oacute;n clara.</p></header><div className="development-grid">{developments.map((item,index)=><article className="development-card" key={item.slug}><Link className="development-media" href={"/contacto?emprendimiento="+item.slug} aria-label={"Consultar por "+item.title}><img src={item.image} alt={item.title}/><span className="development-status">{item.status}</span><b className="development-index">{String(index+1).padStart(2,"0")}</b></Link><div className="development-copy"><p><MapPin aria-hidden="true"/>{item.location}</p><h3><Link href={"/contacto?emprendimiento="+item.slug}>{item.title}</Link></h3><div className="development-meta"><span><Layers3 aria-hidden="true"/><small>UNIDADES</small><b>{item.units}</b></span><span><CalendarDays aria-hidden="true"/><small>ENTREGA</small><b>{item.delivery}</b></span></div><footer><strong>{item.price}</strong><Link href={"/contacto?emprendimiento="+item.slug} aria-label={"Ver "+item.title}><ArrowUpRight aria-hidden="true"/></Link></footer></div></article>)}</div><section className="developments-cta"><Building2 aria-hidden="true"/><div><p>ASESORAMIENTO PARA INVERSORES</p><h2>Eleg&iacute; con informaci&oacute;n.<br/>Invert&iacute; con criterio.</h2></div><Link href="/contacto">Hablemos <ArrowUpRight aria-hidden="true"/></Link></section></section><SiteFooter/></main>;
}