"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { formatPrice, type Property } from "./properties";
import { SiteFooter, SiteHeader } from "./site-chrome";

export function PropertyCard({ property, index }: { property: Property; index: number }) {
  const [favorite, setFavorite] = useState(false);
  return <article className="property-card"><div className="property-media"><img src={property.image} alt={property.title}/><span className="card-index">A/{String(index + 1).padStart(2,"0")}</span><span className="property-tag">{property.operation}</span><button className={`favorite ${favorite ? "active" : ""}`} onClick={()=>setFavorite(!favorite)} type="button">{favorite ? "GUARDADA" : "GUARDAR"}</button></div><div className="property-copy"><div className="card-location"><span>{property.type}</span><span>{property.location}</span></div><h3><Link href={`/propiedades/${property.slug}`}>{property.title}</Link></h3><div className="property-data"><div><b>{property.rooms}</b><span>AMB.</span></div><div><b>{property.bedrooms}</b><span>DORM.</span></div><div><b>{property.area}</b><span>M2</span></div></div><div className="property-footer"><strong>{formatPrice(property)}</strong><Link href={`/propiedades/${property.slug}`}>VER PROPIEDAD <b>+</b></Link></div></div></article>;
}

const services=[["01","Comprar","Busqueda dirigida y negociacion integral."],["02","Vender","Tasacion, narrativa visual y difusion."],["03","Alquilar","Seleccion, documentacion y gestion."],["04","Invertir","Analisis de valor y proyeccion patrimonial."]];
const zones=[["Tigre / Nordelta","84%"],["San Isidro","76%"],["CABA Norte","68%"],["Pilar","61%"]];

export function HomeExperience({ properties }: { properties: Property[] }) {
  const [operation,setOperation]=useState("Venta");
  const [type,setType]=useState("Todos");
  const [zone,setZone]=useState("Todas");
  const [searched,setSearched]=useState(false);
  const visible=useMemo(()=>properties.filter(p=>p.operation===operation&&(type==="Todos"||p.type===type)&&(zone==="Todas"||p.zone===zone)),[operation,type,zone,properties]);
  const runSearch=()=>{setSearched(true);document.getElementById("propiedades")?.scrollIntoView({behavior:"smooth"});};
  return <main><SiteHeader/>
    <section className="hero"><div className="hero-copy"><div className="module-label"><b>01</b><span>BUSQUEDA<br/>INMOBILIARIA</span></div><p className="hero-kicker">PROPIEDADES SELECCIONADAS / ARGENTINA</p><h1>Espacios que<br/><em>construyen valor.</em></h1><p className="hero-summary">Arquitectura, ubicacion y potencial. Una seleccion precisa para comprar, vender e invertir mejor.</p><div className="search-panel"><div className="operation-tabs">{(["Venta","Alquiler"] as const).map(item=><button className={operation===item?"active":""} onClick={()=>setOperation(item)} key={item}>{item.toUpperCase()}</button>)}</div><div className="search-fields"><label><span>TIPO</span><select value={type} onChange={e=>setType(e.target.value)}><option>Todos</option><option>Casa</option><option>Departamento</option><option>PH</option><option>Terreno</option></select></label><label><span>ZONA</span><select value={zone} onChange={e=>setZone(e.target.value)}><option>Todas</option><option>CABA</option><option>Zona Norte</option></select></label><button className="search-button" onClick={runSearch}>BUSCAR <b>+</b></button></div></div></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1800&q=90" alt="Interior contemporaneo"/><div className="hero-property"><span>DESTACADA / A01</span><h2>Casa del Lago</h2><p>NORDELTA / 310 M2</p><Link href="/propiedades/casa-del-lago-nordelta">DESCUBRIR <b>+</b></Link></div><div className="image-coordinate"><span>34.6037 S</span><span>58.3816 W</span></div></div></section>
    <section className="data-band"><div><span>01</span><strong>12</strong><p>A&Ntilde;OS DE<br/>EXPERIENCIA</p></div><div><span>02</span><strong>480</strong><p>OPERACIONES<br/>ACOMPA&Ntilde;ADAS</p></div><div><span>03</span><strong>96%</strong><p>CLIENTES QUE<br/>RECOMIENDAN</p></div><div><span>04</span><strong>16</strong><p>PROPIEDADES<br/>ACTIVAS</p></div></section>
    <section className="method"><div className="method-heading"><div className="module-label dark"><b>02</b><span>NUESTRO<br/>METODO</span></div><h2>Datos para decidir.<br/><em>Criterio para elegir.</em></h2></div><div className="method-grid"><article><span>DIAGNOSTICO</span><b>01</b><h3>Entendemos el objetivo.</h3><p>Necesidad, momento, presupuesto y horizonte de inversion.</p></article><article><span>CURADURIA</span><b>02</b><h3>Reducimos el ruido.</h3><p>Seleccionamos solo activos que superan nuestros criterios.</p></article><article><span>EJECUCION</span><b>03</b><h3>Cerramos con precision.</h3><p>Negociacion, documentacion y seguimiento hasta la firma.</p></article></div></section>
    <section className="properties-section" id="propiedades"><div className="section-heading"><div className="module-label dark"><b>03</b><span>PORTFOLIO<br/>ACTIVO</span></div><div><p>SELECCION ACTUAL</p><h2>{searched?`${visible.length} resultados`:"Propiedades destacadas"}</h2></div><Link className="result-count" href="/propiedades">VER LAS 16 / +</Link></div><div className="filter-row">{(["Venta","Alquiler"] as const).map(item=><button key={item} className={operation===item?"active":""} onClick={()=>setOperation(item)}>{item.toUpperCase()}</button>)}</div><div className="property-grid">{visible.slice(0,6).map((p,i)=><PropertyCard key={p.id} property={p} index={i}/>)}</div></section>
    <section className="market-module"><div className="market-copy"><div className="module-label"><b>04</b><span>LECTURA DE<br/>MERCADO</span></div><h2>Donde esta<br/>el movimiento.</h2><p>Indice visual de demanda relativa dentro de nuestra cartera activa.</p><small>ACTUALIZACION / JUL 2026</small></div><div className="market-chart">{zones.map(([name,value],i)=><div className="chart-row" key={name}><span>0{i+1}</span><b>{name}</b><div><i style={{width:value}}/></div><strong>{value}</strong></div>)}</div></section>
    <section className="services"><div className="section-heading"><div className="module-label dark"><b>05</b><span>SERVICIOS<br/>INTEGRALES</span></div><div><p>DE PUNTA A PUNTA</p><h2>Una estructura.<br/>Todo resuelto.</h2></div><Link className="result-count" href="/servicios">VER DETALLE / +</Link></div><div className="service-grid">{services.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><b>+</b></article>)}</div></section>
    <section className="contact"><div className="module-label"><b>06</b><span>CONTACTO<br/>DIRECTO</span></div><div><p>EMPECEMOS POR UNA CONVERSACION</p><h2>Tu proxima<br/>decision empieza aca.</h2></div><Link href="/contacto">IR A CONTACTO <b>+</b></Link></section><SiteFooter/></main>;
}
