export type Property = {
  id: number; slug: string; title: string; location: string; zone: string;
  operation: "Venta" | "Alquiler" | "Alquiler temporario"; type: "Casa" | "Departamento" | "PH" | "Terreno";
  currency: "USD" | "ARS"; price: number; pricePrefix?: string; priceSuffix?: string; rooms: number; bedrooms: number;
  bathrooms: number; area: number; image: string; featured?: boolean;
  description: string; amenities: string[]; gallery?: string[];
  coveredArea?: number; garages?: number; age?: string; condition?: string; orientation?: string;
};

export const properties: Property[] = [
  { id:1, slug:"casa-del-lago-nordelta", title:"Casa del Lago", location:"Nordelta, Tigre", zone:"Zona Norte", operation:"Venta", type:"Casa", currency:"USD", price:485000, rooms:6, bedrooms:4, bathrooms:3, area:310, image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85", featured:true, description:"Una casa contemporanea abierta al paisaje, con interiores serenos y jardin privado.", amenities:["Piscina","Jardin","Parrilla","Suite","Cochera doble"] },
  { id:2, slug:"residencia-jacaranda-san-isidro", title:"Residencia Jacaranda", location:"San Isidro, Buenos Aires", zone:"Zona Norte", operation:"Venta", type:"Casa", currency:"USD", price:690000, rooms:7, bedrooms:4, bathrooms:4, area:420, image:"https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85", featured:true, description:"Arquitectura noble, materiales calidos y un parque consolidado en San Isidro.", amenities:["Parque","Piscina","Escritorio","Dependencia","Seguridad"] },
  { id:3, slug:"piso-alto-palermo-chico", title:"Piso Alto", location:"Palermo Chico, CABA", zone:"CABA", operation:"Venta", type:"Departamento", currency:"USD", price:355000, rooms:4, bedrooms:3, bathrooms:2, area:138, image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85", featured:true, description:"Un piso luminoso y silencioso, renovado con criterio contemporaneo.", amenities:["Balcon","Palier privado","Cochera","Seguridad 24 h"] },
  { id:4, slug:"loft-distrito-palermo", title:"Loft Distrito", location:"Palermo Hollywood, CABA", zone:"CABA", operation:"Alquiler", type:"Departamento", currency:"ARS", price:1450000, rooms:2, bedrooms:1, bathrooms:1, area:72, image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85", description:"Diseno industrial refinado, doble altura y amenities completos.", amenities:["Pileta","SUM","Gimnasio","Seguridad 24 h"] },
  { id:5, slug:"ph-pasaje-colegiales", title:"PH Pasaje", location:"Colegiales, CABA", zone:"CABA", operation:"Venta", type:"PH", currency:"USD", price:248000, rooms:4, bedrooms:2, bathrooms:2, area:126, image:"https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1600&q=85", description:"Un refugio urbano sin expensas, con patio, terraza y caracter original.", amenities:["Patio","Terraza","Parrilla","Sin expensas"] },
  { id:6, slug:"casa-bosque-pilar", title:"Casa Bosque", location:"Pilar, Buenos Aires", zone:"Zona Norte", operation:"Alquiler", type:"Casa", currency:"USD", price:3200, rooms:6, bedrooms:4, bathrooms:3, area:340, image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85", description:"Naturaleza, privacidad y espacios generosos para una vida familiar.", amenities:["Barrio cerrado","Piscina","Galeria","Parrilla"] },
  { id:7, slug:"torre-rio-puerto-madero", title:"Torre Rio", location:"Puerto Madero, CABA", zone:"CABA", operation:"Venta", type:"Departamento", currency:"USD", price:598000, rooms:4, bedrooms:3, bathrooms:3, area:172, image:"https://images.unsplash.com/photo-1600607688960-e095ff83135c?auto=format&fit=crop&w=1600&q=85", description:"Vistas abiertas al rio, planta generosa y servicios de hoteleria.", amenities:["Vista al rio","Piscina","Gimnasio","Valet parking"] },
  { id:8, slug:"casa-horizonte-vicente-lopez", title:"Casa Horizonte", location:"Vicente Lopez, Buenos Aires", zone:"Zona Norte", operation:"Venta", type:"Casa", currency:"USD", price:540000, rooms:6, bedrooms:4, bathrooms:3, area:295, image:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=85", description:"Lineas puras, luz norte y una terraza proyectada para recibir.", amenities:["Terraza","Piscina","Parrilla","Cochera"] },
  { id:9, slug:"departamento-arce-belgrano", title:"Departamento Arce", location:"Belgrano R, CABA", zone:"CABA", operation:"Alquiler", type:"Departamento", currency:"USD", price:2200, rooms:4, bedrooms:3, bathrooms:2, area:145, image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1600&q=85", description:"Interiores calidos, balcon corrido y excelente conectividad.", amenities:["Balcon","Cochera","Seguridad","Baulera"] },
  { id:10, slug:"terreno-lagos-nordelta", title:"Terreno Lagos", location:"Nordelta, Tigre", zone:"Zona Norte", operation:"Venta", type:"Terreno", currency:"USD", price:265000, rooms:1, bedrooms:1, bathrooms:1, area:980, image:"https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1600&q=85", description:"Lote al agua con orientacion privilegiada y entorno consolidado.", amenities:["Salida al lago","Orientacion norte","Seguridad","Club house"] },
  { id:11, slug:"residencia-la-horqueta", title:"Residencia La Horqueta", location:"San Isidro, Buenos Aires", zone:"Zona Norte", operation:"Venta", type:"Casa", currency:"USD", price:820000, rooms:8, bedrooms:5, bathrooms:4, area:510, image:"https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=1600&q=85", description:"Una residencia clasica actualizada para una vida contemporanea.", amenities:["Parque","Piscina","Quincho","Dependencia","Cava"] },
  { id:12, slug:"ph-patio-villa-urquiza", title:"PH Patio", location:"Villa Urquiza, CABA", zone:"CABA", operation:"Venta", type:"PH", currency:"USD", price:214000, rooms:3, bedrooms:2, bathrooms:2, area:108, image:"https://images.unsplash.com/photo-1600607688066-890987f18a86?auto=format&fit=crop&w=1600&q=85", description:"Patio central, materiales nobles y una reforma funcional.", amenities:["Patio","Terraza","Parrilla","Sin expensas"] },
  { id:13, slug:"piso-libertador-recoleta", title:"Piso Libertador", location:"Recoleta, CABA", zone:"CABA", operation:"Venta", type:"Departamento", currency:"USD", price:445000, rooms:5, bedrooms:3, bathrooms:3, area:190, image:"https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=85", description:"Recepcion amplia, vistas verdes y una ubicacion estrategica.", amenities:["Palier privado","Dependencia","Cochera","Seguridad"] },
  { id:14, slug:"casa-olivos-martinez", title:"Casa Olivos", location:"Martinez, Buenos Aires", zone:"Zona Norte", operation:"Alquiler", type:"Casa", currency:"USD", price:4500, rooms:7, bedrooms:4, bathrooms:4, area:390, image:"https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=85", description:"Volumenes amplios, jardin maduro y privacidad en una calle tranquila.", amenities:["Piscina","Jardin","Galeria","Seguridad"] },
  { id:15, slug:"duplex-las-canitas", title:"Duplex Canitas", location:"Las Canitas, CABA", zone:"CABA", operation:"Alquiler", type:"Departamento", currency:"USD", price:2800, rooms:4, bedrooms:2, bathrooms:2, area:132, image:"https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1600&q=85", description:"Doble altura, terraza propia y diseno de autor.", amenities:["Terraza","Parrilla","Cochera","Pileta"] },
  { id:16, slug:"casa-pradera-pilar", title:"Casa Pradera", location:"Pilar, Buenos Aires", zone:"Zona Norte", operation:"Venta", type:"Casa", currency:"USD", price:398000, rooms:6, bedrooms:4, bathrooms:3, area:325, image:"https://images.unsplash.com/photo-1600047509358-9dc75507daeb?auto=format&fit=crop&w=1600&q=85", description:"Una casa luminosa con galeria profunda y vistas al verde.", amenities:["Barrio cerrado","Piscina","Galeria","Cochera doble"] }
];

export const formatPrice = (property: Property) => [property.pricePrefix?.trim(), `${property.currency} ${new Intl.NumberFormat("es-AR").format(property.price)}`, property.priceSuffix?.trim()].filter(Boolean).join(" ");
