export type Property = {
  id: number; slug: string; title: string; location: string; zone: string;
  operation: "Venta" | "Alquiler"; type: "Casa" | "Departamento" | "PH" | "Terreno";
  currency: "USD" | "ARS"; price: number; rooms: number; bedrooms: number;
  bathrooms: number; area: number; image: string; featured?: boolean;
  description: string; amenities: string[];
};

export const properties: Property[] = [
  { id: 1, slug: "casa-del-lago-nordelta", title: "Casa del Lago", location: "Nordelta, Tigre", zone: "Zona Norte", operation: "Venta", type: "Casa", currency: "USD", price: 485000, rooms: 6, bedrooms: 4, bathrooms: 3, area: 310, image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85", featured: true, description: "Una casa contemporánea abierta al paisaje, con interiores serenos, jardín privado y una relación excepcional entre luz y espacio.", amenities: ["Piscina", "Jardín", "Parrilla", "Suite", "Cochera doble"] },
  { id: 2, slug: "residencia-jacaranda-san-isidro", title: "Residencia Jacarandá", location: "San Isidro, Buenos Aires", zone: "Zona Norte", operation: "Venta", type: "Casa", currency: "USD", price: 690000, rooms: 7, bedrooms: 4, bathrooms: 4, area: 420, image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85", featured: true, description: "Arquitectura noble, materiales cálidos y un parque consolidado en una de las zonas residenciales más buscadas de San Isidro.", amenities: ["Parque", "Piscina", "Escritorio", "Dependencia", "Seguridad"] },
  { id: 3, slug: "piso-alto-palermo-chico", title: "Piso Alto", location: "Palermo Chico, CABA", zone: "CABA", operation: "Venta", type: "Departamento", currency: "USD", price: 355000, rooms: 4, bedrooms: 3, bathrooms: 2, area: 138, image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1600&q=85", featured: true, description: "Un piso luminoso y silencioso, renovado con criterio contemporáneo y vistas abiertas sobre la ciudad.", amenities: ["Balcón", "Palier privado", "Cochera", "Seguridad 24 h"] },
  { id: 4, slug: "loft-distrito-palermo", title: "Loft Distrito", location: "Palermo Hollywood, CABA", zone: "CABA", operation: "Alquiler", type: "Departamento", currency: "ARS", price: 1450000, rooms: 2, bedrooms: 1, bathrooms: 1, area: 72, image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85", description: "Diseño industrial refinado, doble altura y amenities completos en el corazón creativo de Palermo.", amenities: ["Pileta", "SUM", "Gimnasio", "Seguridad 24 h"] },
  { id: 5, slug: "ph-pasaje-colegiales", title: "PH Pasaje", location: "Colegiales, CABA", zone: "CABA", operation: "Venta", type: "PH", currency: "USD", price: 248000, rooms: 4, bedrooms: 2, bathrooms: 2, area: 126, image: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1600&q=85", description: "Un refugio urbano sin expensas, con patio, terraza y una reforma que conserva el carácter original.", amenities: ["Patio", "Terraza", "Parrilla", "Sin expensas"] },
  { id: 6, slug: "casa-bosque-pilar", title: "Casa Bosque", location: "Pilar, Buenos Aires", zone: "Zona Norte", operation: "Alquiler", type: "Casa", currency: "USD", price: 3200, rooms: 6, bedrooms: 4, bathrooms: 3, area: 340, image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85", description: "Naturaleza, privacidad y espacios generosos para una vida familiar conectada con el exterior.", amenities: ["Barrio cerrado", "Piscina", "Galería", "Parrilla"] }
];

export const formatPrice = (property: Property) => `${property.currency} ${new Intl.NumberFormat("es-AR").format(property.price)}`;
